### ISSUE TITLE
Scheduled upward merges for numbered branches in qa-integration-framework repository - Fortnight #5

### ISSUE THREAD

**Issue by rauldpm** [wazuh/qa-integration-framework#108]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.0-into-4.8.1`.

### 4.7.3
- [x] ~Update changelog.~ Not needed
- [x] ~Merge branch `4.7.3` into branch `4.8.0`.~ Not needed, 4.8.0 and 4.7.3 are identical:
![image](https://github.com/wazuh/qa-integration-framework/assets/23361101/cf0156c7-b49e-4875-b319-136e333a85c7)

### 4.8.0
- [ ] Update changelog.
- [ ] Merge branch `4.8.0` into branch `4.8.1`. 
### 4.8.1
- [ ] Update changelog. 
- [ ] Merge branch `4.8.1` into branch `4.8.2`. 
### 4.8.2
- [ ] Update changelog.
- [ ] Merge branch `4.8.2` into branch `4.9.0`. 
### 4.9.0
- [ ] Update changelog.
- [ ] Merge branch `4.9.0` into branch `master`. 
### 5.0.0 (master)
- [ ] Update changelog.

**Comment by Selutario** [comment]
Done in:
- https://github.com/wazuh/qa-integration-framework/issues/111
