### ISSUE TITLE
Scheduled upward merges for numbered branches in qa-integration-framework repository - Fortnight #11

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/qa-integration-framework#198]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.1-into-4.9.0`.

### 4.8.1
- [x] Update changelog.
- [x] Merge branch `4.8.1` into branch `4.9.0`.

**Comment by fdalmaup** [comment]
Not needed, branches are identical:

![image](https://github.com/wazuh/qa-integration-framework/assets/26691145/d01c36a3-d3c0-4e6f-961a-b8df39233fae)
