### ISSUE TITLE
Migrate and refactor AWS module to new qa testing framework

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/qa-integration-framework#36]
| Affected integration |
|---|
| AWS|

## Description 

As part of [Wazuh epic #17788](https://github.com/wazuh/wazuh/issues/17788), the current AWS module used to run AWS ITs found in wazuh-qa needs to be migrated and adapted to the new qa testing framework. 

Some of the changes are:

Task are:

- [x] Migrate the aws module to new framework.
- [x] Update requirements file.
- [x] Update modules imports. 
- [x] Migration of the constants found in `modules/aws/__init__.py` to the framework-specified paths. Ex: `wazuh_testing/constants/paths/aws.py`
- [x] Migrate test specific configuration to the corresponding test folder in `wazuh`.
- [x] Refactor all utils files to unified into a single util file.
- [x] Refactor db_utils to use the framework database manager.

**Comment by Selutario** [comment]
ETA postponed to `06/10/2023`. Reason:
- The reviewer (DRI) is out of office.
