### ISSUE TITLE
Remove all references to vulnerability detector in the wazuh_testing package

### ISSUE THREAD

**Issue by mhamra** [wazuh/qa-integration-framework#87]
As part of the vulnerability detector requested by wazuh issue [# 21461](https://github.com/wazuh/wazuh/issues/21461), it is required to remove the references to the vulnerability detector in the wazuh_testing package.

**Comment by mhamra** [comment]
### UPDATE
The following [PR comment](https://github.com/wazuh/wazuh/pull/21542#issuecomment-1904953319) shows the test_api tier 0-1 execution results using the `wazuh_testing` package version modified by this issue. All tests passed successfully.

**Comment by Selutario** [comment]
Closing this, the reason can be found here: https://github.com/wazuh/qa-integration-framework/pull/88#pullrequestreview-1843506345
